# Shared paths and run identity for GR00T N1.5 RoboCasa shell recipes.

GROOT_N15_CONFIG_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
GROOT_N15_REPO_ROOT="${GROOT_N15_REPO_ROOT:-${REPO_ROOT:-$(cd -- "${GROOT_N15_CONFIG_DIR}/../../../.." && pwd)}}"
GROOT_N15_CONTAINER_REPO_ROOT="${GROOT_N15_CONTAINER_REPO_ROOT:-${CONTAINER_REPO_ROOT:-/temporal_vla}}"

GROOT_N15_OUT_ROOT="${GROOT_N15_OUT_ROOT:-${GROOT_N15_REPO_ROOT}/outputs/eval/robocasa/groot_n15}"
GROOT_N15_OUT_ROOT_CONTAINER="${GROOT_N15_OUT_ROOT_CONTAINER:-${GROOT_N15_CONTAINER_REPO_ROOT}/outputs/eval/robocasa/groot_n15}"

GROOT_N15_TARGET15_RUN_ID="${GROOT_N15_TARGET15_RUN_ID:-${RUN_ID:-$(date +%Y%m%d_%H%M%S)}}"
GROOT_N15_TARGET15_RUN_ROOT="${GROOT_N15_TARGET15_RUN_ROOT:-${GROOT_N15_OUT_ROOT}/target15_seedpairs_${GROOT_N15_TARGET15_RUN_ID}}"
GROOT_N15_TARGET15_RUN_ROOT_CONTAINER="${GROOT_N15_TARGET15_RUN_ROOT_CONTAINER:-${GROOT_N15_OUT_ROOT_CONTAINER}/target15_seedpairs_${GROOT_N15_TARGET15_RUN_ID}}"

GROOT_N15_BASE_NEW_EMBODIMENT_CHECKPOINT="${GROOT_N15_BASE_NEW_EMBODIMENT_CHECKPOINT:-${GROOT_N15_REPO_ROOT}/outputs/checkpoints/groot_n15_base_pandaomron_new_embodiment}"
GROOT_N15_BASE_NEW_EMBODIMENT_CHECKPOINT_CONTAINER="${GROOT_N15_BASE_NEW_EMBODIMENT_CHECKPOINT_CONTAINER:-${GROOT_N15_CONTAINER_REPO_ROOT}/outputs/checkpoints/groot_n15_base_pandaomron_new_embodiment}"

GROOT_N15_SEEN5_SOURCE_ROOT="${GROOT_N15_SEEN5_SOURCE_ROOT:-${GROOT_N15_OUT_ROOT}/rollouts_seen5_100ep_per_task_subset100}"
GROOT_N15_SEEN5_SPLIT_ROOT="${GROOT_N15_SEEN5_SPLIT_ROOT:-${GROOT_N15_OUT_ROOT}/split_seen5_trainval75_cp15_test10_subset100}"
