# Shared paths and run identity for GR00T N1.6 RoboCasa SAFE shell recipes.

ROBOCASA_SAFE_CONFIG_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROBOCASA_SAFE_REPO_ROOT="${ROBOCASA_SAFE_REPO_ROOT:-${REPO_ROOT:-$(cd -- "${ROBOCASA_SAFE_CONFIG_DIR}/../../../.." && pwd)}}"
ROBOCASA_SAFE_WORKSPACE_ROOT="${ROBOCASA_SAFE_WORKSPACE_ROOT:-$(cd -- "${ROBOCASA_SAFE_REPO_ROOT}/.." && pwd)}"

ROBOCASA_SAFE_OUT_ROOT="${ROBOCASA_SAFE_OUT_ROOT:-${ROBOCASA_SAFE_REPO_ROOT}/outputs/eval/robocasa/groot_n16}"
ROBOCASA_SAFE_RUN_ID="${ROBOCASA_SAFE_RUN_ID:-safe_seen4_unseen2_100ep}"
ROBOCASA_SAFE_RUN_ROOT="${ROBOCASA_SAFE_RUN_ROOT:-${ROBOCASA_SAFE_OUT_ROOT}/${ROBOCASA_SAFE_RUN_ID}}"

ROBOCASA_SAFE_EXPERIMENT_ID="${ROBOCASA_SAFE_EXPERIMENT_ID:-seen4_unseen2_openDrawer_pnpCab_100ep}"
ROBOCASA_SAFE_SUBSET_NAME="${ROBOCASA_SAFE_SUBSET_NAME:-robocasa_${ROBOCASA_SAFE_EXPERIMENT_ID}}"

ROBOCASA_SAFE_FINAL_HORIZON_IDX_REL="${ROBOCASA_SAFE_FINAL_HORIZON_IDX_REL:-mean}"
ROBOCASA_SAFE_FINAL_DIFF_IDX_REL="${ROBOCASA_SAFE_FINAL_DIFF_IDX_REL:-concat-2}"
ROBOCASA_SAFE_FINAL_AGGREGATION_SLUG="${ROBOCASA_SAFE_FINAL_AGGREGATION_SLUG:-hmean_dconcat2}"
ROBOCASA_SAFE_HPARAM_SWEEP_ID="${ROBOCASA_SAFE_HPARAM_SWEEP_ID:-hparam_sweep_${ROBOCASA_SAFE_FINAL_AGGREGATION_SLUG}_v2}"
